apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  creationTimestamp: null
  labels:
    owner: jstrachan
    provider: github
    repository: nodey420
  name: jstrachan-nodey420
spec:
  description: Imported application for jstrachan/nodey420
  httpCloneURL: https://github.com/jstrachan/nodey420.git
  org: jstrachan
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: nodey420
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/jstrachan/nodey420.git
